version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/barry/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-
    
  express:
    image: node:18.13.0
    container_name: express
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./api/bin:/usr/src/app/bin
      - ./api/src:/usr/src/app/src
      - ./api/package.json:/usr/src/app/package.json
      - ./api/package-lock.json:/usr/src/app/package-lock.json
      - ./api/node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

  react:
    image: node:18.13.0
    container_name: react
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/package.json:/usr/src/app/package.json
      - ./client/package-lock.json:/usr/src/app/package-lock.json
      - ./client/node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    command: bash -c "npm install && npm start"